// npm run build:core — package the shared core for the WeChat mini program.
//
// The web app is untouched by this script. It emits, into dist-core/:
//   deuceline-domain.js     CommonJS bundle of src/domain (validate + derive +
//                           add/replace) for the mini program pages to `require`.
//   deuceline-publisher.js  CommonJS bundle of the publish core + GitHub store
//                           (functions/api/_mp-publisher.ts) for CloudBase cloud
//                           functions (Node 18+).
//   deuceline-tokens.wxss   The default skin's design tokens (src/styles/skins.css
//                           `:root` block) re-scoped to `page` for WXSS.
// Then it self-checks the domain bundle against the real dataset, and — only if
// the mini program folders exist — copies the files into them:
//   miniprogram/lib/        ← deuceline-domain.js, deuceline-tokens.wxss
//   cloudfunctions/<fn>/lib/ ← deuceline-publisher.js
// Those copies are generated: rebuild, never hand-edit. See MINIPROGRAM.md.

import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "vite";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "dist-core");
const { version } = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const banner = `/* GENERATED by \`npm run build:core\` from Deuceline v${version} — do not edit. Source: see MINIPROGRAM.md. */`;

async function bundle(name, entry, emptyOutDir) {
  await build({
    configFile: false,
    root,
    // Only the bundle belongs in dist-core; don't copy public/ alongside it.
    publicDir: false,
    logLevel: "warn",
    build: {
      outDir,
      emptyOutDir,
      // Conservative syntax target for the mini program JS engines; runtime
      // APIs are not polyfilled, which is why src/domain stays plain ES2018-era.
      target: "es2018",
      minify: false,
      lib: { entry: join(root, entry), formats: ["cjs"], fileName: () => `${name}.js` },
      rollupOptions: { output: { exports: "named" } },
    },
  });
  // Stamp the header ourselves: Vite's lib build drops rollup's `banner`.
  const file = join(outDir, `${name}.js`);
  writeFileSync(file, `${banner}\n${readFileSync(file, "utf8")}`);
}

await bundle("deuceline-domain", "src/domain/index.ts", true);
await bundle("deuceline-publisher", "functions/api/_mp-publisher.ts", false);

// The repo is "type": "module"; mark dist-core as CommonJS so Node (and the
// self-check below) load the .js bundles the way the mini program does.
writeFileSync(join(outDir, "package.json"), `${JSON.stringify({ type: "commonjs" }, null, 2)}\n`);

// Design tokens: the default skin block is the single owner of chrome colour.
// WXSS has no :root or attribute selectors, so re-scope it to `page`.
const skins = readFileSync(join(root, "src/styles/skins.css"), "utf8");
const defaultSkin = skins.match(/:root,\s*\[data-skin="wimbledon"\]\s*\{([\s\S]*?)\n\}/);
if (!defaultSkin) throw new Error("build:core: could not find the default :root skin block in skins.css");
const tokens = defaultSkin[1].replace(/\/\*[\s\S]*?\*\//g, "").replace(/\n\s*\n/g, "\n").trimEnd();
writeFileSync(
  join(outDir, "deuceline-tokens.wxss"),
  `${banner}\n/* Chrome tokens from src/styles/skins.css. Player identity colours are NOT here — read them from the dataset. */\npage {${tokens}\n}\n`,
);

// Self-check: the bundle must validate and derive from the real dataset.
const require = createRequire(import.meta.url);
const domain = require(join(outDir, "deuceline-domain.js"));
const dataset = domain.validateDataset(JSON.parse(readFileSync(join(root, "public/data/deuceline-data.json"), "utf8")));
const stats = domain.deriveOverviewStats(dataset.matches);
const publisher = require(join(outDir, "deuceline-publisher.js"));
for (const name of ["checkPublishKey", "handleAddMatch", "handleUpdateMatch", "handleGetDataset", "createGitHubStore"]) {
  if (typeof publisher[name] !== "function") throw new Error(`build:core: publisher bundle is missing ${name}`);
}
console.log(`build:core ✓ v${version}: dataset valid, H2H ${stats.matchRecord.alan}–${stats.matchRecord.opponent} over ${stats.totalMatches} finished matches`);

// Sync into the mini program tree when it exists (created by the port, not here).
function copyInto(dir, files) {
  mkdirSync(dir, { recursive: true });
  for (const file of files) copyFileSync(join(outDir, file), join(dir, file));
  console.log(`  → ${dir.slice(root.length + 1)}/ (${files.join(", ")})`);
}

if (existsSync(join(root, "miniprogram"))) {
  copyInto(join(root, "miniprogram/lib"), ["deuceline-domain.js", "deuceline-tokens.wxss"]);
}
const functionsRoot = join(root, "cloudfunctions");
if (existsSync(functionsRoot)) {
  for (const name of readdirSync(functionsRoot)) {
    const dir = join(functionsRoot, name);
    if (statSync(dir).isDirectory()) copyInto(join(dir, "lib"), ["deuceline-publisher.js"]);
  }
}
