/* GENERATED by `npm run build:core` from Deuceline v0.11.6 — do not edit. Source: see MINIPROGRAM.md. */
"use strict";
Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
const SURFACES = ["hard", "clay", "grass", "astro"];
const WEATHER_TAGS = ["sunny", "cloudy", "windy", "hot"];
const emptyRecord = () => ({ alan: 0, opponent: 0 });
const surfaceRecord = () => Object.fromEntries(
  SURFACES.map((surface) => [
    surface,
    { played: 0, alan: 0, opponent: 0, setsAlan: 0, setsOpponent: 0, decidersAlan: 0, decidersOpponent: 0 }
  ])
);
function sortMatchesNewestFirst(matches) {
  return [...matches].sort((a, b) => b.seq - a.seq);
}
const isUnfinished = (match) => match.status === "unfinished";
function deriveSetWinner(set) {
  return set.alan > set.opponent ? "alan" : "opponent";
}
function formatSetScore(set) {
  const base = `${set.alan}-${set.opponent}`;
  if (!set.tiebreak) return base;
  return `${base} (${set.tiebreak.alan}-${set.tiebreak.opponent})`;
}
function matchScoreFromSets(sets) {
  const score = emptyRecord();
  sets.forEach((set) => {
    score[deriveSetWinner(set)] += 1;
  });
  return score;
}
function deriveMatchResult(match) {
  const matchScore = match.fidelity === "sets" ? matchScoreFromSets(match.sets) : { ...match.matchScore };
  const totalSets = matchScore.alan + matchScore.opponent;
  const setScores = match.fidelity === "sets" ? match.sets.map(formatSetScore) : null;
  const hasSetDetail = match.fidelity === "sets";
  if (isUnfinished(match)) {
    return { winner: null, isUnfinished: true, matchScore, setScores, hasSetDetail, isDecider: false };
  }
  return {
    // Tied match scores are rejected by validateDataset (for finished matches).
    winner: matchScore.alan > matchScore.opponent ? "alan" : "opponent",
    isUnfinished: false,
    matchScore,
    setScores,
    hasSetDetail,
    isDecider: totalSets >= 3 && Math.abs(matchScore.alan - matchScore.opponent) === 1
  };
}
function formatMatchScore(match) {
  const { matchScore } = deriveMatchResult(match);
  return `${matchScore.alan}—${matchScore.opponent}`;
}
function formatWinnerScoreline(match) {
  const result = deriveMatchResult(match);
  if (result.winner === null) {
    throw new Error(`formatWinnerScoreline called on an unfinished match: ${match.id}`);
  }
  const loser = result.winner === "alan" ? "opponent" : "alan";
  const setScores = match.fidelity !== "sets" ? null : match.sets.map(
    (set) => result.winner === "alan" ? formatSetScore(set) : formatSetScore({
      alan: set.opponent,
      opponent: set.alan,
      tiebreak: set.tiebreak ? { alan: set.tiebreak.opponent, opponent: set.tiebreak.alan } : void 0
    })
  );
  return {
    winner: result.winner,
    score: `${result.matchScore[result.winner]}—${result.matchScore[loser]}`,
    setScores
  };
}
function formatNeutralScoreline(match) {
  const result = deriveMatchResult(match);
  return {
    alan: result.matchScore.alan,
    opponent: result.matchScore.opponent,
    setScores: match.fidelity === "sets" ? match.sets.map(formatSetScore) : null
  };
}
function deriveOverviewStats(matches) {
  const sortedMatches = sortMatchesNewestFirst(matches).filter((match) => !isUnfinished(match));
  const results = sortedMatches.map((match) => ({
    match,
    result: deriveMatchResult(match)
  }));
  const matchRecord = emptyRecord();
  const setRecord = emptyRecord();
  const deciderRecord = emptyRecord();
  const surfaceSplit = surfaceRecord();
  let detailedMatchCount = 0;
  for (const { match, result } of results) {
    matchRecord[result.winner] += 1;
    setRecord.alan += result.matchScore.alan;
    setRecord.opponent += result.matchScore.opponent;
    if (result.isDecider) deciderRecord[result.winner] += 1;
    if (result.hasSetDetail) detailedMatchCount += 1;
    surfaceSplit[match.surface].played += 1;
    surfaceSplit[match.surface][result.winner] += 1;
    surfaceSplit[match.surface].setsAlan += result.matchScore.alan;
    surfaceSplit[match.surface].setsOpponent += result.matchScore.opponent;
    if (result.isDecider) {
      surfaceSplit[match.surface][result.winner === "alan" ? "decidersAlan" : "decidersOpponent"] += 1;
    }
  }
  const recentForm = results.slice(0, 5).map(({ match, result }) => ({
    matchId: match.id,
    winner: result.winner
  }));
  const timeline = deriveTimeline(matches);
  const currentStreak = deriveCurrentStreak(results);
  const streakHistory = deriveStreakHistory(results);
  const surfaceStreak = Object.fromEntries(
    SURFACES.map((surface) => [surface, deriveCurrentStreak(results.filter((entry) => entry.match.surface === surface))])
  );
  return {
    // Finished matches only — sortedMatches already excludes unfinished ones.
    totalMatches: sortedMatches.length,
    detailedMatchCount,
    matchRecord,
    setRecord,
    deciderRecord,
    currentStreak,
    recentForm,
    surfaceSplit,
    streakHistory,
    surfaceStreak,
    timeline,
    coverage: deriveDataCoverage(matches),
    sortedMatches
  };
}
function deriveDataCoverage(matches) {
  const finished = matches.filter((match) => !isUnfinished(match));
  return {
    finishedMatches: finished.length,
    datedMatches: finished.filter((match) => match.date !== void 0).length,
    detailedScoreMatches: finished.filter((match) => match.fidelity === "sets").length,
    weatherMatches: finished.filter((match) => {
      var _a, _b;
      return ((_b = (_a = match.conditions) == null ? void 0 : _a.length) != null ? _b : 0) > 0 || match.tempC !== void 0;
    }).length
  };
}
function deriveMatchContext(matches, matchId) {
  const target = matches.find((match) => match.id === matchId);
  if (!target) throw new Error(`Unknown match id: ${matchId}`);
  if (isUnfinished(target)) {
    throw new Error(`Cannot derive rivalry impact for an unfinished match: ${matchId}`);
  }
  const ordered = matches.filter((match) => !isUnfinished(match)).sort((a, b) => a.seq - b.seq);
  const index = ordered.findIndex((match) => match.id === matchId);
  const winners = ordered.map((match) => deriveMatchResult(match).winner);
  const winner = winners[index];
  const recordBefore = emptyRecord();
  for (let i = 0; i < index; i += 1) recordBefore[winners[i]] += 1;
  const recordAfter = { ...recordBefore };
  recordAfter[winner] += 1;
  let streakCount = 0;
  for (let i = index; i >= 0 && winners[i] === winner; i -= 1) streakCount += 1;
  let snappedStreak = null;
  if (index > 0 && winners[index - 1] !== winner) {
    const player = winners[index - 1];
    let count = 0;
    for (let i = index - 1; i >= 0 && winners[i] === player; i -= 1) count += 1;
    if (count >= 2) snappedStreak = { player, count };
  }
  return {
    matchNumber: index + 1,
    totalMatches: ordered.length,
    winner,
    recordBefore,
    recordAfter,
    streakAfter: { winner, count: streakCount },
    snappedStreak
  };
}
function deriveStreakHistory(results) {
  const runs = [];
  for (const { result } of results) {
    const lastRun = runs[runs.length - 1];
    if (lastRun && lastRun.winner === result.winner) {
      lastRun.count += 1;
    } else {
      runs.push({ winner: result.winner, count: 1 });
    }
  }
  return runs;
}
function deriveCurrentStreak(results) {
  if (results.length === 0) return { winner: null, count: 0 };
  const winner = results[0].result.winner;
  let count = 0;
  for (const { result } of results) {
    if (result.winner !== winner) break;
    count += 1;
  }
  return { winner, count };
}
function deriveTimeline(matches) {
  const ordered = matches.filter((match) => !isUnfinished(match)).sort((a, b) => a.seq - b.seq);
  const cumulative = emptyRecord();
  const winners = [];
  return ordered.map((match) => {
    var _a;
    const winner = deriveMatchResult(match).winner;
    winners.push(winner);
    cumulative[winner] += 1;
    const window = winners.slice(-5);
    const alanWins = window.filter((w) => w === "alan").length;
    return {
      seq: match.seq,
      matchId: match.id,
      date: (_a = match.date) != null ? _a : null,
      winner,
      cumulative: { ...cumulative },
      lead: cumulative.alan - cumulative.opponent,
      rollingWinRateAlan: alanWins / window.length
    };
  });
}
function matchGamesTally(match) {
  return match.sets.reduce(
    (games, set) => ({
      alan: games.alan + set.alan,
      opponent: games.opponent + set.opponent
    }),
    emptyRecord()
  );
}
function deriveGamesTally(matches) {
  const finished = matches.filter((match) => !isUnfinished(match));
  const detailed = finished.filter((match) => match.fidelity === "sets").sort((a, b) => a.seq - b.seq);
  const games = emptyRecord();
  let biggestSetMargin = null;
  detailed.forEach((match) => {
    const matchGames = matchGamesTally(match);
    games.alan += matchGames.alan;
    games.opponent += matchGames.opponent;
    match.sets.forEach((set) => {
      const winner = deriveSetWinner(set);
      const loser = winner === "alan" ? "opponent" : "alan";
      const margin = set[winner] - set[loser];
      if (!biggestSetMargin || margin > biggestSetMargin.margin) {
        const winnerFirst = winner === "alan" ? set : {
          alan: set.opponent,
          opponent: set.alan,
          tiebreak: set.tiebreak ? { alan: set.tiebreak.opponent, opponent: set.tiebreak.alan } : void 0
        };
        biggestSetMargin = {
          matchId: match.id,
          score: formatSetScore(winnerFirst),
          winner,
          margin
        };
      }
    });
  });
  return {
    games,
    detailedMatchCount: detailed.length,
    finishedMatchCount: finished.length,
    biggestSetMargin
  };
}
function deriveScorelineDistribution(matches) {
  const finished = matches.filter((match) => !isUnfinished(match));
  const straightSets = emptyRecord();
  const deciders = emptyRecord();
  let totalSets = 0;
  finished.forEach((match) => {
    const result = deriveMatchResult(match);
    const loser = result.winner === "alan" ? "opponent" : "alan";
    totalSets += result.matchScore.alan + result.matchScore.opponent;
    if (result.matchScore[loser] === 0) straightSets[result.winner] += 1;
    if (result.isDecider) deciders[result.winner] += 1;
  });
  return {
    straightSets,
    deciders,
    averageSetsPerMatch: finished.length ? totalSets / finished.length : null,
    finishedMatchCount: finished.length
  };
}
function longestRun(streakHistory, player) {
  return streakHistory.reduce((longest, run) => run.winner === player ? Math.max(longest, run.count) : longest, 0);
}
function maxLead(timeline) {
  const extremes = { alan: null, opponent: null };
  timeline.forEach((point) => {
    if (point.lead > 0 && (!extremes.alan || point.lead > extremes.alan.lead)) {
      extremes.alan = { lead: point.lead, matchId: point.matchId, seq: point.seq };
    }
    const opponentLead = -point.lead;
    if (opponentLead > 0 && (!extremes.opponent || opponentLead > extremes.opponent.lead)) {
      extremes.opponent = { lead: opponentLead, matchId: point.matchId, seq: point.seq };
    }
  });
  return extremes;
}
function deriveSurfaceForm(matches, surface, limit = 5) {
  return sortMatchesNewestFirst(matches).filter((match) => !isUnfinished(match) && match.surface === surface).slice(0, Math.max(0, limit)).map((match) => ({
    matchId: match.id,
    winner: deriveMatchResult(match).winner
  }));
}
const MS_PER_DAY = 864e5;
function parseIsoDay(iso) {
  const [year, month, day] = iso.split("-").map(Number);
  return new Date(year, month - 1, day);
}
const startOfDay = (date) => new Date(date.getFullYear(), date.getMonth(), date.getDate());
function deriveCadence(matches, now) {
  const finished = matches.filter((match) => !isUnfinished(match));
  const dated = finished.filter((match) => typeof match.date === "string").map((match) => ({ date: match.date, day: parseIsoDay(match.date) })).sort((a, b) => a.day.getTime() - b.day.getTime());
  const undatedCount = finished.length - dated.length;
  if (dated.length === 0) {
    return {
      datedCount: 0,
      undatedCount,
      lastMatchDate: null,
      daysSinceLast: null,
      playedLast30: 0,
      playedLast90: 0,
      longestGapDays: null,
      longestGap: null
    };
  }
  const today = startOfDay(now).getTime();
  const last = dated[dated.length - 1];
  const daysAgo = (day) => Math.round((today - day.getTime()) / MS_PER_DAY);
  const within = (days) => dated.filter((entry) => {
    const ago = daysAgo(entry.day);
    return ago >= 0 && ago <= days;
  }).length;
  let longestGapDays = null;
  let longestGap = null;
  for (let i = 1; i < dated.length; i += 1) {
    const gap = Math.round((dated[i].day.getTime() - dated[i - 1].day.getTime()) / MS_PER_DAY);
    if (longestGapDays === null || gap > longestGapDays) {
      longestGapDays = gap;
      longestGap = { fromDate: dated[i - 1].date, toDate: dated[i].date };
    }
  }
  return {
    datedCount: dated.length,
    undatedCount,
    lastMatchDate: last.date,
    daysSinceLast: daysAgo(last.day),
    playedLast30: within(30),
    playedLast90: within(90),
    longestGapDays,
    longestGap
  };
}
class DatasetValidationError extends Error {
  constructor(issues) {
    super(`Invalid Deuceline dataset:
${issues.join("\n")}`);
    this.issues = issues;
    this.name = "DatasetValidationError";
  }
}
function validateDataset(value) {
  const issues = [];
  if (!isRecord(value)) {
    throw new DatasetValidationError(["Dataset must be an object."]);
  }
  validateKnownKeys(value, "dataset", ["schemaVersion", "rivalry", "matches"], issues);
  if (value.schemaVersion !== 2) {
    issues.push("schemaVersion must be 2.");
  }
  const rivalry = value.rivalry;
  if (!isRecord(rivalry)) {
    issues.push("rivalry must exist.");
  } else {
    validateKnownKeys(rivalry, "rivalry", ["id", "title", "players"], issues);
    if (!isNonEmptyString(rivalry.id)) issues.push("rivalry.id is required.");
    if (!isNonEmptyString(rivalry.title)) issues.push("rivalry.title is required.");
    validatePlayers(rivalry.players, issues);
  }
  if (!Array.isArray(value.matches)) {
    issues.push("matches must be an array.");
  } else {
    validateMatches(value.matches, issues);
  }
  if (issues.length > 0) {
    throw new DatasetValidationError(issues);
  }
  return value;
}
function validatePlayers(value, issues) {
  if (!isRecord(value)) {
    issues.push("rivalry.players must exist.");
    return;
  }
  validateKnownKeys(value, "rivalry.players", ["alan", "opponent"], issues);
  ["alan", "opponent"].forEach((playerKey) => {
    const player = value[playerKey];
    if (!isRecord(player)) {
      issues.push(`rivalry.players.${playerKey} must exist.`);
      return;
    }
    validateKnownKeys(player, `rivalry.players.${playerKey}`, ["displayName", "color", "abbr"], issues);
    if (!isNonEmptyString(player.displayName)) {
      issues.push(`rivalry.players.${playerKey}.displayName is required.`);
    }
    if (!isHexColor(player.color)) {
      issues.push(`rivalry.players.${playerKey}.color must be a hex color like #b85c3d.`);
    }
    if (!isNonEmptyString(player.abbr)) {
      issues.push(`rivalry.players.${playerKey}.abbr is required.`);
    }
  });
}
function validateMatches(matches, issues) {
  const ids = /* @__PURE__ */ new Set();
  const seqs = /* @__PURE__ */ new Set();
  matches.forEach((match, index) => {
    var _a;
    if (!isRecord(match)) {
      issues.push(`matches[${index}] must be an object.`);
      return;
    }
    const label = matchLabel(match, index);
    validateKnownKeys(match, label, matchKeys(match), issues);
    const id = String((_a = match.id) != null ? _a : "");
    if (!isNonEmptyString(match.id)) {
      issues.push(`matches[${index}].id is required.`);
    } else if (ids.has(id)) {
      issues.push(`Duplicate match id: ${id}.`);
    } else {
      ids.add(id);
    }
    if (!isPositiveInteger(match.seq)) {
      issues.push(`${label} seq must be a positive integer.`);
    } else if (seqs.has(match.seq)) {
      issues.push(`Duplicate match seq: ${match.seq}.`);
    } else {
      seqs.add(match.seq);
    }
    if (match.date !== void 0 && !isIsoDate(match.date)) {
      issues.push(`${label} date must be YYYY-MM-DD when present.`);
    }
    if (typeof match.surface !== "string" || !SURFACES.includes(match.surface)) {
      issues.push(`${label} surface must be hard, clay, grass, or astro.`);
    }
    if (match.location !== void 0 && typeof match.location !== "string") {
      issues.push(`${label} location must be a string.`);
    }
    if (match.notes !== void 0 && typeof match.notes !== "string") {
      issues.push(`${label} notes must be a string.`);
    }
    validateConditions(match.conditions, label, issues);
    if (match.tempC !== void 0 && (typeof match.tempC !== "number" || !Number.isFinite(match.tempC) || match.tempC < -30 || match.tempC > 55)) {
      issues.push(`${label} tempC must be a number between -30 and 55 when present.`);
    }
    if (match.status !== void 0 && match.status !== "unfinished") {
      issues.push(`${label} status must be "unfinished" when present.`);
    }
    validateFidelity(match, label, issues);
  });
}
function validateConditions(value, label, issues) {
  if (value === void 0) return;
  if (!Array.isArray(value)) {
    issues.push(`${label} conditions must be an array when present.`);
    return;
  }
  const seen = /* @__PURE__ */ new Set();
  value.forEach((tag) => {
    if (typeof tag !== "string" || !WEATHER_TAGS.includes(tag)) {
      issues.push(`${label} conditions has unknown weather tag: ${String(tag)}.`);
    } else if (seen.has(tag)) {
      issues.push(`${label} conditions has a duplicate weather tag: ${tag}.`);
    } else {
      seen.add(tag);
    }
  });
}
function validateFidelity(match, label, issues) {
  const isUnfinished2 = match.status === "unfinished";
  if (match.fidelity === "sets") {
    validateSets(match.sets, label, issues, isUnfinished2);
  } else if (match.fidelity === "matchScore") {
    validateMatchScore(match.matchScore, label, issues, isUnfinished2);
  } else {
    issues.push(`${label} fidelity must be "sets" or "matchScore".`);
  }
}
function validateSets(value, label, issues, isUnfinished2) {
  if (!Array.isArray(value) || value.length === 0) {
    issues.push(`${label} sets must be a non-empty array.`);
    return;
  }
  value.forEach((set, index) => {
    validateSetScore(set, `${label} sets[${index}]`, issues);
  });
  const typedSets = value.filter(isValidSetShape);
  if (typedSets.length !== value.length) return;
  if (typedSets.some((set) => set.alan === set.opponent)) {
    issues.push(`${label} cannot include a tied set.`);
    return;
  }
  if (isUnfinished2) return;
  const tally = { alan: 0, opponent: 0 };
  typedSets.forEach((set) => {
    tally[deriveSetWinner(set)] += 1;
  });
  if (tally.alan === tally.opponent) {
    issues.push(`${label} cannot end with a tied match score.`);
  }
}
function validateMatchScore(value, label, issues, isUnfinished2) {
  if (!isRecord(value)) {
    issues.push(`${label} matchScore must be an object.`);
    return;
  }
  validateKnownKeys(value, `${label} matchScore`, ["alan", "opponent"], issues);
  const { alan, opponent } = value;
  if (!isNonNegativeInteger(alan) || !isNonNegativeInteger(opponent)) {
    if (!isNonNegativeInteger(alan)) issues.push(`${label} matchScore.alan must be a non-negative integer.`);
    if (!isNonNegativeInteger(opponent)) issues.push(`${label} matchScore.opponent must be a non-negative integer.`);
    return;
  }
  if (!isUnfinished2 && alan === opponent) {
    issues.push(`${label} matchScore cannot be tied.`);
  }
  if (alan + opponent === 0) {
    issues.push(`${label} matchScore must record at least one set.`);
  }
}
function validateSetScore(value, label, issues) {
  if (!isRecord(value)) {
    issues.push(`${label} must be an object.`);
    return;
  }
  validateKnownKeys(value, label, ["alan", "opponent", "tiebreak"], issues);
  if (!isNonNegativeInteger(value.alan)) issues.push(`${label}.alan must be a non-negative integer.`);
  if (!isNonNegativeInteger(value.opponent)) issues.push(`${label}.opponent must be a non-negative integer.`);
  if (value.tiebreak !== void 0) {
    if (!isRecord(value.tiebreak)) {
      issues.push(`${label}.tiebreak must be an object.`);
    } else {
      validateKnownKeys(value.tiebreak, `${label}.tiebreak`, ["alan", "opponent"], issues);
      if (!isNonNegativeInteger(value.tiebreak.alan)) issues.push(`${label}.tiebreak.alan must be a non-negative integer.`);
      if (!isNonNegativeInteger(value.tiebreak.opponent)) issues.push(`${label}.tiebreak.opponent must be a non-negative integer.`);
    }
  }
}
function validateKnownKeys(value, label, allowedKeys, issues) {
  const allowed = new Set(allowedKeys);
  Object.keys(value).forEach((key) => {
    if (!allowed.has(key)) {
      issues.push(`${label} has unknown field: ${key}.`);
    }
  });
}
function matchKeys(match) {
  const baseKeys = ["id", "seq", "date", "surface", "location", "conditions", "tempC", "notes", "status", "fidelity"];
  if (match.fidelity === "sets") return [...baseKeys, "sets"];
  if (match.fidelity === "matchScore") return [...baseKeys, "matchScore"];
  return [...baseKeys, "sets", "matchScore"];
}
function isValidSetShape(value) {
  return isRecord(value) && isNonNegativeInteger(value.alan) && isNonNegativeInteger(value.opponent);
}
function isRecord(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
function isNonEmptyString(value) {
  return typeof value === "string" && value.trim().length > 0;
}
function isHexColor(value) {
  return typeof value === "string" && /^#[0-9a-fA-F]{6}$/.test(value);
}
function isNonNegativeInteger(value) {
  return typeof value === "number" && Number.isInteger(value) && value >= 0;
}
function isPositiveInteger(value) {
  return typeof value === "number" && Number.isInteger(value) && value >= 1;
}
function isIsoDate(value) {
  if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return false;
  const date = /* @__PURE__ */ new Date(`${value}T00:00:00Z`);
  return !Number.isNaN(date.valueOf()) && date.toISOString().slice(0, 10) === value;
}
function matchLabel(match, index) {
  return isNonEmptyString(match.id) ? `match ${match.id}` : `matches[${index}]`;
}
function buildMatchBody(input, identity) {
  var _a, _b;
  return {
    id: identity.id,
    seq: identity.seq,
    ...input.date ? { date: input.date } : {},
    surface: input.surface,
    ...((_a = input.location) == null ? void 0 : _a.trim()) ? { location: input.location.trim() } : {},
    ...input.conditions && input.conditions.length > 0 ? { conditions: input.conditions } : {},
    ...input.tempC !== void 0 ? { tempC: input.tempC } : {},
    fidelity: input.fidelity,
    ...input.fidelity === "sets" ? { sets: input.sets } : { matchScore: input.matchScore },
    ...input.status ? { status: input.status } : {},
    ...((_b = input.notes) == null ? void 0 : _b.trim()) ? { notes: input.notes.trim() } : {}
  };
}
function appendMatch(dataset, input) {
  const seq = dataset.matches.reduce((max, match2) => Math.max(max, match2.seq), 0) + 1;
  const ids = new Set(dataset.matches.map((match2) => match2.id));
  let idNumber = seq;
  while (ids.has(`match-${idNumber}`)) idNumber += 1;
  const match = buildMatchBody(input, { id: `match-${idNumber}`, seq });
  return { ...dataset, matches: [...dataset.matches, match] };
}
function replaceMatch(dataset, id, input) {
  const index = dataset.matches.findIndex((match) => match.id === id);
  if (index === -1) throw new Error(`Unknown match id: ${id}`);
  const existing = dataset.matches[index];
  const next = buildMatchBody(input, { id: existing.id, seq: existing.seq });
  const matches = dataset.matches.map((match, i) => i === index ? next : match);
  return { ...dataset, matches };
}
function serializeDataset(dataset) {
  return `${JSON.stringify(dataset, null, 2)}
`;
}
exports.DatasetValidationError = DatasetValidationError;
exports.SURFACES = SURFACES;
exports.WEATHER_TAGS = WEATHER_TAGS;
exports.appendMatch = appendMatch;
exports.deriveCadence = deriveCadence;
exports.deriveDataCoverage = deriveDataCoverage;
exports.deriveGamesTally = deriveGamesTally;
exports.deriveMatchContext = deriveMatchContext;
exports.deriveMatchResult = deriveMatchResult;
exports.deriveOverviewStats = deriveOverviewStats;
exports.deriveScorelineDistribution = deriveScorelineDistribution;
exports.deriveSetWinner = deriveSetWinner;
exports.deriveSurfaceForm = deriveSurfaceForm;
exports.deriveTimeline = deriveTimeline;
exports.formatMatchScore = formatMatchScore;
exports.formatNeutralScoreline = formatNeutralScoreline;
exports.formatSetScore = formatSetScore;
exports.formatWinnerScoreline = formatWinnerScoreline;
exports.isUnfinished = isUnfinished;
exports.longestRun = longestRun;
exports.matchGamesTally = matchGamesTally;
exports.maxLead = maxLead;
exports.replaceMatch = replaceMatch;
exports.serializeDataset = serializeDataset;
exports.sortMatchesNewestFirst = sortMatchesNewestFirst;
exports.validateDataset = validateDataset;
