/* GENERATED by `npm run build:core` from Deuceline v0.13.0 — do not edit. Source: see MINIPROGRAM.md. */
"use strict";
Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
const SURFACES = ["hard", "clay", "grass", "astro"];
const WEATHER_TAGS = ["sunny", "cloudy", "windy", "hot"];
const emptyRecord$1 = () => ({ alan: 0, opponent: 0 });
const surfaceRecord = () => Object.fromEntries(
  SURFACES.map((surface) => [
    surface,
    { played: 0, alan: 0, opponent: 0, setsAlan: 0, setsOpponent: 0, decidersAlan: 0, decidersOpponent: 0 }
  ])
);
function sortMatchesNewestFirst(matches) {
  return [...matches].sort((a, b) => b.seq - a.seq);
}
const isUnfinished = (match) => match.status === "unfinished";
function deriveSetWinner(set) {
  return set.alan > set.opponent ? "alan" : "opponent";
}
function formatSetScore(set) {
  const base = `${set.alan}-${set.opponent}`;
  if (!set.tiebreak) return base;
  return `${base} (${set.tiebreak.alan}-${set.tiebreak.opponent})`;
}
function formatMatchTiebreak(points) {
  return `[${points.alan}-${points.opponent}]`;
}
const flipPoints = (points) => ({ alan: points.opponent, opponent: points.alan });
const flipSet = (set) => ({
  alan: set.opponent,
  opponent: set.alan,
  tiebreak: set.tiebreak ? flipPoints(set.tiebreak) : void 0
});
function detailedSetScores(match, flip = false) {
  const scores = match.sets.map((set) => formatSetScore(flip ? flipSet(set) : set));
  if (match.matchTiebreak) {
    scores.push(formatMatchTiebreak(flip ? flipPoints(match.matchTiebreak) : match.matchTiebreak));
  }
  return scores;
}
function matchScoreFromSets(match) {
  const score = emptyRecord$1();
  match.sets.forEach((set) => {
    score[deriveSetWinner(set)] += 1;
  });
  if (match.matchTiebreak) score[deriveSetWinner(match.matchTiebreak)] += 1;
  return score;
}
function deriveMatchResult(match) {
  const matchScore = match.fidelity === "sets" ? matchScoreFromSets(match) : { ...match.matchScore };
  const totalSets = matchScore.alan + matchScore.opponent;
  const setScores = match.fidelity === "sets" ? detailedSetScores(match) : null;
  const hasSetDetail = match.fidelity === "sets";
  if (isUnfinished(match)) {
    return { winner: null, isUnfinished: true, matchScore, setScores, hasSetDetail, isDecider: false };
  }
  return {
    // Tied match scores are rejected by validateDataset (for finished matches).
    winner: matchScore.alan > matchScore.opponent ? "alan" : "opponent",
    isUnfinished: false,
    matchScore,
    setScores,
    hasSetDetail,
    isDecider: totalSets >= 3 && Math.abs(matchScore.alan - matchScore.opponent) === 1
  };
}
function fullSetsWon(match) {
  if (match.fidelity !== "sets") return { ...match.matchScore };
  const sets = emptyRecord$1();
  match.sets.forEach((set) => {
    sets[deriveSetWinner(set)] += 1;
  });
  return sets;
}
function deriveMatchShape(match) {
  const result = deriveMatchResult(match);
  if (result.winner === null) return null;
  const loser = result.winner === "alan" ? "opponent" : "alan";
  if (result.matchScore[loser] === 0) return "straight";
  if (!result.isDecider) return "other";
  if (match.fidelity !== "sets") return "scoreOnlyDecider";
  return match.matchTiebreak ? "superTiebreak" : "thirdSet";
}
function formatMatchScore(match) {
  const { matchScore } = deriveMatchResult(match);
  return `${matchScore.alan}—${matchScore.opponent}`;
}
function formatWinnerScoreline(match) {
  const result = deriveMatchResult(match);
  if (result.winner === null) {
    throw new Error(`formatWinnerScoreline called on an unfinished match: ${match.id}`);
  }
  const loser = result.winner === "alan" ? "opponent" : "alan";
  const setScores = match.fidelity !== "sets" ? null : detailedSetScores(match, result.winner !== "alan");
  return {
    winner: result.winner,
    score: `${result.matchScore[result.winner]}—${result.matchScore[loser]}`,
    setScores
  };
}
function formatNeutralScoreline(match) {
  const result = deriveMatchResult(match);
  return {
    alan: result.matchScore.alan,
    opponent: result.matchScore.opponent,
    setScores: match.fidelity === "sets" ? detailedSetScores(match) : null
  };
}
function deriveOverviewStats(matches) {
  const sortedMatches = sortMatchesNewestFirst(matches).filter((match) => !isUnfinished(match));
  const results = sortedMatches.map((match) => ({
    match,
    result: deriveMatchResult(match)
  }));
  const matchRecord = emptyRecord$1();
  const setRecord = emptyRecord$1();
  const deciderRecord = emptyRecord$1();
  const surfaceSplit = surfaceRecord();
  let detailedMatchCount = 0;
  for (const { match, result } of results) {
    const sets = fullSetsWon(match);
    matchRecord[result.winner] += 1;
    setRecord.alan += sets.alan;
    setRecord.opponent += sets.opponent;
    if (result.isDecider) deciderRecord[result.winner] += 1;
    if (result.hasSetDetail) detailedMatchCount += 1;
    surfaceSplit[match.surface].played += 1;
    surfaceSplit[match.surface][result.winner] += 1;
    surfaceSplit[match.surface].setsAlan += sets.alan;
    surfaceSplit[match.surface].setsOpponent += sets.opponent;
    if (result.isDecider) {
      surfaceSplit[match.surface][result.winner === "alan" ? "decidersAlan" : "decidersOpponent"] += 1;
    }
  }
  const recentForm = results.slice(0, 5).map(({ match, result }) => ({
    matchId: match.id,
    winner: result.winner
  }));
  const timeline = deriveTimeline(matches);
  const currentStreak = deriveCurrentStreak(results);
  const streakHistory = deriveStreakHistory(results);
  const surfaceStreak = Object.fromEntries(
    SURFACES.map((surface) => [surface, deriveCurrentStreak(results.filter((entry) => entry.match.surface === surface))])
  );
  return {
    // Finished matches only — sortedMatches already excludes unfinished ones.
    totalMatches: sortedMatches.length,
    detailedMatchCount,
    matchRecord,
    setRecord,
    deciderRecord,
    currentStreak,
    recentForm,
    surfaceSplit,
    streakHistory,
    surfaceStreak,
    timeline,
    coverage: deriveDataCoverage(matches),
    sortedMatches
  };
}
function deriveDataCoverage(matches) {
  const finished = matches.filter((match) => !isUnfinished(match));
  return {
    finishedMatches: finished.length,
    datedMatches: finished.filter((match) => match.date !== void 0).length,
    detailedScoreMatches: finished.filter((match) => match.fidelity === "sets").length,
    weatherMatches: finished.filter((match) => {
      var _a, _b;
      return ((_b = (_a = match.conditions) == null ? void 0 : _a.length) != null ? _b : 0) > 0 || match.tempC !== void 0;
    }).length
  };
}
function deriveMatchContext(matches, matchId) {
  const target = matches.find((match) => match.id === matchId);
  if (!target) throw new Error(`Unknown match id: ${matchId}`);
  if (isUnfinished(target)) {
    throw new Error(`Cannot derive rivalry impact for an unfinished match: ${matchId}`);
  }
  const ordered = matches.filter((match) => !isUnfinished(match)).sort((a, b) => a.seq - b.seq);
  const index = ordered.findIndex((match) => match.id === matchId);
  const winners = ordered.map((match) => deriveMatchResult(match).winner);
  const winner = winners[index];
  const recordBefore = emptyRecord$1();
  for (let i = 0; i < index; i += 1) recordBefore[winners[i]] += 1;
  const recordAfter = { ...recordBefore };
  recordAfter[winner] += 1;
  let streakCount = 0;
  for (let i = index; i >= 0 && winners[i] === winner; i -= 1) streakCount += 1;
  let snappedStreak = null;
  if (index > 0 && winners[index - 1] !== winner) {
    const player = winners[index - 1];
    let count = 0;
    for (let i = index - 1; i >= 0 && winners[i] === player; i -= 1) count += 1;
    if (count >= 2) snappedStreak = { player, count };
  }
  return {
    matchNumber: index + 1,
    totalMatches: ordered.length,
    winner,
    recordBefore,
    recordAfter,
    streakAfter: { winner, count: streakCount },
    snappedStreak
  };
}
function deriveStreakHistory(results) {
  const runs = [];
  for (const { result } of results) {
    const lastRun = runs[runs.length - 1];
    if (lastRun && lastRun.winner === result.winner) {
      lastRun.count += 1;
    } else {
      runs.push({ winner: result.winner, count: 1 });
    }
  }
  return runs;
}
function deriveCurrentStreak(results) {
  if (results.length === 0) return { winner: null, count: 0 };
  const winner = results[0].result.winner;
  let count = 0;
  for (const { result } of results) {
    if (result.winner !== winner) break;
    count += 1;
  }
  return { winner, count };
}
function deriveTimeline(matches) {
  const ordered = matches.filter((match) => !isUnfinished(match)).sort((a, b) => a.seq - b.seq);
  const cumulative = emptyRecord$1();
  const winners = [];
  return ordered.map((match) => {
    var _a;
    const winner = deriveMatchResult(match).winner;
    winners.push(winner);
    cumulative[winner] += 1;
    const window = winners.slice(-5);
    const alanWins = window.filter((w) => w === "alan").length;
    return {
      seq: match.seq,
      matchId: match.id,
      date: (_a = match.date) != null ? _a : null,
      winner,
      cumulative: { ...cumulative },
      lead: cumulative.alan - cumulative.opponent,
      rollingWinRateAlan: alanWins / window.length
    };
  });
}
function matchGamesTally(match) {
  return match.sets.reduce(
    (games, set) => ({
      alan: games.alan + set.alan,
      opponent: games.opponent + set.opponent
    }),
    emptyRecord$1()
  );
}
function deriveGamesTally(matches) {
  const finished = matches.filter((match) => !isUnfinished(match));
  const detailed = finished.filter((match) => match.fidelity === "sets").sort((a, b) => a.seq - b.seq);
  const games = emptyRecord$1();
  let biggestSetMargin = null;
  detailed.forEach((match) => {
    const matchGames = matchGamesTally(match);
    games.alan += matchGames.alan;
    games.opponent += matchGames.opponent;
    match.sets.forEach((set) => {
      const winner = deriveSetWinner(set);
      const loser = winner === "alan" ? "opponent" : "alan";
      const margin = set[winner] - set[loser];
      if (!biggestSetMargin || margin > biggestSetMargin.margin) {
        biggestSetMargin = {
          matchId: match.id,
          score: formatSetScore(winner === "alan" ? set : flipSet(set)),
          winner,
          margin
        };
      }
    });
  });
  return {
    games,
    detailedMatchCount: detailed.length,
    finishedMatchCount: finished.length,
    biggestSetMargin
  };
}
const emptyShapes = () => ({
  straight: emptyRecord$1(),
  superTiebreak: emptyRecord$1(),
  thirdSet: emptyRecord$1(),
  scoreOnlyDecider: emptyRecord$1(),
  other: emptyRecord$1()
});
function deriveScorelineDistribution(matches) {
  const finished = sortMatchesNewestFirst(matches).filter((match) => !isUnfinished(match));
  const byShape = emptyShapes();
  const deciders = emptyRecord$1();
  const points = emptyRecord$1();
  let closest = null;
  finished.forEach((match) => {
    const result = deriveMatchResult(match);
    const shape = deriveMatchShape(match);
    byShape[shape][result.winner] += 1;
    if (result.isDecider) deciders[result.winner] += 1;
    if (match.fidelity === "sets" && match.matchTiebreak) {
      const tiebreak = match.matchTiebreak;
      points.alan += tiebreak.alan;
      points.opponent += tiebreak.opponent;
      const winner = deriveSetWinner(tiebreak);
      const loser = winner === "alan" ? "opponent" : "alan";
      const margin = tiebreak[winner] - tiebreak[loser];
      if (!closest || margin < closest.margin) {
        closest = { matchId: match.id, seq: match.seq, score: `${tiebreak[winner]}-${tiebreak[loser]}`, winner, margin };
      }
    }
  });
  return {
    straightSets: byShape.straight,
    deciders,
    byShape,
    deciderCount: deciders.alan + deciders.opponent,
    finishedMatchCount: finished.length,
    superTiebreak: { record: byShape.superTiebreak, points, closest }
  };
}
function deriveFirstSetConversion(matches) {
  const finished = sortMatchesNewestFirst(matches).filter((match) => !isUnfinished(match));
  const firstSetWins = emptyRecord$1();
  const converted = emptyRecord$1();
  const comebacks = emptyRecord$1();
  const comebackMatchIds = [];
  let sample = 0;
  finished.forEach((match) => {
    if (match.fidelity !== "sets" || match.sets.length < 2) return;
    sample += 1;
    const winner = deriveMatchResult(match).winner;
    const firstSetWinner = deriveSetWinner(match.sets[0]);
    firstSetWins[firstSetWinner] += 1;
    if (firstSetWinner === winner) {
      converted[winner] += 1;
    } else {
      comebacks[winner] += 1;
      comebackMatchIds.push(match.id);
    }
  });
  return { sample, finishedMatchCount: finished.length, firstSetWins, converted, comebacks, comebackMatchIds };
}
function longestRun(streakHistory, player) {
  return streakHistory.reduce((longest, run) => run.winner === player ? Math.max(longest, run.count) : longest, 0);
}
function maxLead(timeline) {
  const extremes = { alan: null, opponent: null };
  timeline.forEach((point) => {
    if (point.lead > 0 && (!extremes.alan || point.lead > extremes.alan.lead)) {
      extremes.alan = { lead: point.lead, matchId: point.matchId, seq: point.seq };
    }
    const opponentLead = -point.lead;
    if (opponentLead > 0 && (!extremes.opponent || opponentLead > extremes.opponent.lead)) {
      extremes.opponent = { lead: opponentLead, matchId: point.matchId, seq: point.seq };
    }
  });
  return extremes;
}
function deriveSurfaceForm(matches, surface, limit = 5) {
  return sortMatchesNewestFirst(matches).filter((match) => !isUnfinished(match) && match.surface === surface).slice(0, Math.max(0, limit)).map((match) => ({
    matchId: match.id,
    winner: deriveMatchResult(match).winner
  }));
}
const MS_PER_DAY = 864e5;
function parseIsoDay(iso) {
  const [year, month, day] = iso.split("-").map(Number);
  return new Date(year, month - 1, day);
}
const startOfDay = (date) => new Date(date.getFullYear(), date.getMonth(), date.getDate());
function deriveCadence(matches, now) {
  const finished = matches.filter((match) => !isUnfinished(match));
  const dated = finished.filter((match) => typeof match.date === "string").map((match) => ({ date: match.date, day: parseIsoDay(match.date) })).sort((a, b) => a.day.getTime() - b.day.getTime());
  const undatedCount = finished.length - dated.length;
  if (dated.length === 0) {
    return {
      datedCount: 0,
      undatedCount,
      lastMatchDate: null,
      daysSinceLast: null,
      playedLast30: 0,
      playedLast90: 0,
      longestGapDays: null,
      longestGap: null
    };
  }
  const today = startOfDay(now).getTime();
  const last = dated[dated.length - 1];
  const daysAgo = (day) => Math.round((today - day.getTime()) / MS_PER_DAY);
  const within = (days) => dated.filter((entry) => {
    const ago = daysAgo(entry.day);
    return ago >= 0 && ago <= days;
  }).length;
  let longestGapDays = null;
  let longestGap = null;
  for (let i = 1; i < dated.length; i += 1) {
    const gap = Math.round((dated[i].day.getTime() - dated[i - 1].day.getTime()) / MS_PER_DAY);
    if (longestGapDays === null || gap > longestGapDays) {
      longestGapDays = gap;
      longestGap = { fromDate: dated[i - 1].date, toDate: dated[i].date };
    }
  }
  return {
    datedCount: dated.length,
    undatedCount,
    lastMatchDate: last.date,
    daysSinceLast: daysAgo(last.day),
    playedLast30: within(30),
    playedLast90: within(90),
    longestGapDays,
    longestGap
  };
}
class DatasetValidationError extends Error {
  constructor(issues) {
    super(`Invalid Deuceline dataset:
${issues.join("\n")}`);
    this.issues = issues;
    this.name = "DatasetValidationError";
  }
}
function validateDataset(value) {
  const issues = [];
  if (!isRecord(value)) {
    throw new DatasetValidationError(["Dataset must be an object."]);
  }
  validateKnownKeys(value, "dataset", ["schemaVersion", "rivalry", "matches"], issues);
  if (value.schemaVersion !== 2) {
    issues.push("schemaVersion must be 2.");
  }
  const rivalry = value.rivalry;
  if (!isRecord(rivalry)) {
    issues.push("rivalry must exist.");
  } else {
    validateKnownKeys(rivalry, "rivalry", ["id", "title", "players"], issues);
    if (!isNonEmptyString(rivalry.id)) issues.push("rivalry.id is required.");
    if (!isNonEmptyString(rivalry.title)) issues.push("rivalry.title is required.");
    validatePlayers(rivalry.players, issues);
  }
  if (!Array.isArray(value.matches)) {
    issues.push("matches must be an array.");
  } else {
    validateMatches(value.matches, issues);
  }
  if (issues.length > 0) {
    throw new DatasetValidationError(issues);
  }
  return value;
}
function validatePlayers(value, issues) {
  if (!isRecord(value)) {
    issues.push("rivalry.players must exist.");
    return;
  }
  validateKnownKeys(value, "rivalry.players", ["alan", "opponent"], issues);
  ["alan", "opponent"].forEach((playerKey) => {
    const player = value[playerKey];
    if (!isRecord(player)) {
      issues.push(`rivalry.players.${playerKey} must exist.`);
      return;
    }
    validateKnownKeys(player, `rivalry.players.${playerKey}`, ["displayName", "color", "abbr"], issues);
    if (!isNonEmptyString(player.displayName)) {
      issues.push(`rivalry.players.${playerKey}.displayName is required.`);
    }
    if (!isHexColor(player.color)) {
      issues.push(`rivalry.players.${playerKey}.color must be a hex color like #b85c3d.`);
    }
    if (!isNonEmptyString(player.abbr)) {
      issues.push(`rivalry.players.${playerKey}.abbr is required.`);
    }
  });
}
function validateMatches(matches, issues) {
  const ids = /* @__PURE__ */ new Set();
  const seqs = /* @__PURE__ */ new Set();
  matches.forEach((match, index) => {
    var _a;
    if (!isRecord(match)) {
      issues.push(`matches[${index}] must be an object.`);
      return;
    }
    const label = matchLabel(match, index);
    validateKnownKeys(match, label, matchKeys(match), issues);
    const id = String((_a = match.id) != null ? _a : "");
    if (!isNonEmptyString(match.id)) {
      issues.push(`matches[${index}].id is required.`);
    } else if (ids.has(id)) {
      issues.push(`Duplicate match id: ${id}.`);
    } else {
      ids.add(id);
    }
    if (!isPositiveInteger(match.seq)) {
      issues.push(`${label} seq must be a positive integer.`);
    } else if (seqs.has(match.seq)) {
      issues.push(`Duplicate match seq: ${match.seq}.`);
    } else {
      seqs.add(match.seq);
    }
    if (match.date !== void 0 && !isIsoDate(match.date)) {
      issues.push(`${label} date must be YYYY-MM-DD when present.`);
    }
    if (typeof match.surface !== "string" || !SURFACES.includes(match.surface)) {
      issues.push(`${label} surface must be hard, clay, grass, or astro.`);
    }
    if (match.location !== void 0 && typeof match.location !== "string") {
      issues.push(`${label} location must be a string.`);
    }
    if (match.notes !== void 0 && typeof match.notes !== "string") {
      issues.push(`${label} notes must be a string.`);
    }
    validateConditions(match.conditions, label, issues);
    if (match.tempC !== void 0 && (typeof match.tempC !== "number" || !Number.isFinite(match.tempC) || match.tempC < -30 || match.tempC > 55)) {
      issues.push(`${label} tempC must be a number between -30 and 55 when present.`);
    }
    if (match.status !== void 0 && match.status !== "unfinished") {
      issues.push(`${label} status must be "unfinished" when present.`);
    }
    validateFidelity(match, label, issues);
  });
}
function validateConditions(value, label, issues) {
  if (value === void 0) return;
  if (!Array.isArray(value)) {
    issues.push(`${label} conditions must be an array when present.`);
    return;
  }
  const seen = /* @__PURE__ */ new Set();
  value.forEach((tag) => {
    if (typeof tag !== "string" || !WEATHER_TAGS.includes(tag)) {
      issues.push(`${label} conditions has unknown weather tag: ${String(tag)}.`);
    } else if (seen.has(tag)) {
      issues.push(`${label} conditions has a duplicate weather tag: ${tag}.`);
    } else {
      seen.add(tag);
    }
  });
}
function validateFidelity(match, label, issues) {
  const isUnfinished2 = match.status === "unfinished";
  if (match.fidelity === "sets") {
    validateSets(match.sets, match.matchTiebreak, label, issues, isUnfinished2);
  } else if (match.fidelity === "matchScore") {
    validateMatchScore(match.matchScore, label, issues, isUnfinished2);
  } else {
    issues.push(`${label} fidelity must be "sets" or "matchScore".`);
  }
}
function validateSets(value, matchTiebreak, label, issues, isUnfinished2) {
  if (!Array.isArray(value) || value.length === 0) {
    issues.push(`${label} sets must be a non-empty array.`);
    return;
  }
  value.forEach((set, index) => {
    validateSetScore(set, `${label} sets[${index}]`, issues);
  });
  const hasMatchTiebreak = matchTiebreak !== void 0;
  if (hasMatchTiebreak) validatePoints(matchTiebreak, `${label} matchTiebreak`, issues);
  const typedSets = value.filter(isValidSetShape);
  if (typedSets.length !== value.length) return;
  if (typedSets.some((set) => set.alan === set.opponent)) {
    issues.push(`${label} cannot include a tied set.`);
    return;
  }
  typedSets.forEach((set, index) => {
    const mayBeInProgress = isUnfinished2 && !hasMatchTiebreak && index === typedSets.length - 1;
    validateSetRules(set, `${label} sets[${index}]`, issues, mayBeInProgress);
  });
  const tally = { alan: 0, opponent: 0 };
  for (const set of typedSets) {
    if (tally.alan === 2 || tally.opponent === 2) {
      issues.push(`${label} has a set after the match was already won (best of three).`);
      break;
    }
    tally[deriveSetWinner(set)] += 1;
  }
  if (hasMatchTiebreak) {
    if (isUnfinished2) {
      issues.push(`${label} matchTiebreak decides the match, so the match cannot be unfinished.`);
    }
    if (typedSets.length !== 2 || tally.alan !== 1 || tally.opponent !== 1) {
      issues.push(`${label} matchTiebreak is only played at one set all, after exactly two sets.`);
    }
    if (isValidPointShape(matchTiebreak)) {
      const problem = tiebreakPointsProblem(matchTiebreak, 10);
      if (problem) issues.push(`${label} matchTiebreak ${problem}.`);
      else tally[deriveSetWinner(matchTiebreak)] += 1;
    }
  }
  if (isUnfinished2 || hasMatchTiebreak) return;
  if (tally.alan === tally.opponent) {
    issues.push(`${label} cannot end with a tied match score.`);
  }
}
function validateSetRules(set, label, issues, mayBeInProgress) {
  const winner = deriveSetWinner(set);
  const won = set[winner];
  const lost = set[winner === "alan" ? "opponent" : "alan"];
  const isComplete = won === 6 && lost <= 4 || won === 7 && (lost === 5 || lost === 6);
  const isInProgress = won <= 5 || won === 6 && lost === 5;
  if (!isComplete && !(mayBeInProgress && isInProgress)) {
    issues.push(`${label} ${set.alan}-${set.opponent} is not a valid set score (6-0 to 6-4, 7-5 or 7-6).`);
  }
  if (set.tiebreak !== void 0 && isValidPointShape(set.tiebreak)) {
    if (!(won === 7 && lost === 6)) {
      issues.push(`${label}.tiebreak is only allowed on a 7-6 set.`);
      return;
    }
    const problem = tiebreakPointsProblem(set.tiebreak, 7);
    if (problem) {
      issues.push(`${label}.tiebreak ${problem}.`);
    } else if (deriveSetWinner(set.tiebreak) !== winner) {
      issues.push(`${label}.tiebreak must be won by the player who won the set.`);
    }
  }
}
function tiebreakPointsProblem(points, target) {
  const high = Math.max(points.alan, points.opponent);
  const low = Math.min(points.alan, points.opponent);
  if (high === low) return "cannot be tied";
  if (high < target) return `must be won by reaching ${target} points`;
  if (high - low < 2) return "must be won by two clear points";
  if (high > target && high - low !== 2) return `past ${target} points must end exactly two points apart`;
  return null;
}
function validateMatchScore(value, label, issues, isUnfinished2) {
  if (!isRecord(value)) {
    issues.push(`${label} matchScore must be an object.`);
    return;
  }
  validateKnownKeys(value, `${label} matchScore`, ["alan", "opponent"], issues);
  const { alan, opponent } = value;
  if (!isNonNegativeInteger(alan) || !isNonNegativeInteger(opponent)) {
    if (!isNonNegativeInteger(alan)) issues.push(`${label} matchScore.alan must be a non-negative integer.`);
    if (!isNonNegativeInteger(opponent)) issues.push(`${label} matchScore.opponent must be a non-negative integer.`);
    return;
  }
  if (!isUnfinished2 && alan === opponent) {
    issues.push(`${label} matchScore cannot be tied.`);
  }
  if (alan + opponent === 0) {
    issues.push(`${label} matchScore must record at least one set.`);
  }
}
function validateSetScore(value, label, issues) {
  if (!isRecord(value)) {
    issues.push(`${label} must be an object.`);
    return;
  }
  validateKnownKeys(value, label, ["alan", "opponent", "tiebreak"], issues);
  if (!isNonNegativeInteger(value.alan)) issues.push(`${label}.alan must be a non-negative integer.`);
  if (!isNonNegativeInteger(value.opponent)) issues.push(`${label}.opponent must be a non-negative integer.`);
  if (value.tiebreak !== void 0) validatePoints(value.tiebreak, `${label}.tiebreak`, issues);
}
function validatePoints(value, label, issues) {
  if (!isRecord(value)) {
    issues.push(`${label} must be an object.`);
    return;
  }
  validateKnownKeys(value, label, ["alan", "opponent"], issues);
  if (!isNonNegativeInteger(value.alan)) issues.push(`${label}.alan must be a non-negative integer.`);
  if (!isNonNegativeInteger(value.opponent)) issues.push(`${label}.opponent must be a non-negative integer.`);
}
function validateKnownKeys(value, label, allowedKeys, issues) {
  const allowed = new Set(allowedKeys);
  Object.keys(value).forEach((key) => {
    if (!allowed.has(key)) {
      issues.push(`${label} has unknown field: ${key}.`);
    }
  });
}
function matchKeys(match) {
  const baseKeys = ["id", "seq", "date", "surface", "location", "conditions", "tempC", "notes", "status", "fidelity"];
  if (match.fidelity === "sets") return [...baseKeys, "sets", "matchTiebreak"];
  if (match.fidelity === "matchScore") return [...baseKeys, "matchScore"];
  return [...baseKeys, "sets", "matchTiebreak", "matchScore"];
}
function isValidSetShape(value) {
  return isRecord(value) && isNonNegativeInteger(value.alan) && isNonNegativeInteger(value.opponent);
}
function isValidPointShape(value) {
  return isValidSetShape(value);
}
function isRecord(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
function isNonEmptyString(value) {
  return typeof value === "string" && value.trim().length > 0;
}
function isHexColor(value) {
  return typeof value === "string" && /^#[0-9a-fA-F]{6}$/.test(value);
}
function isNonNegativeInteger(value) {
  return typeof value === "number" && Number.isInteger(value) && value >= 0;
}
function isPositiveInteger(value) {
  return typeof value === "number" && Number.isInteger(value) && value >= 1;
}
function isIsoDate(value) {
  if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return false;
  const date = /* @__PURE__ */ new Date(`${value}T00:00:00Z`);
  return !Number.isNaN(date.valueOf()) && date.toISOString().slice(0, 10) === value;
}
function matchLabel(match, index) {
  return isNonEmptyString(match.id) ? `match ${match.id}` : `matches[${index}]`;
}
function buildMatchBody(input, identity) {
  var _a, _b;
  return {
    id: identity.id,
    seq: identity.seq,
    ...input.date ? { date: input.date } : {},
    surface: input.surface,
    ...((_a = input.location) == null ? void 0 : _a.trim()) ? { location: input.location.trim() } : {},
    ...input.conditions && input.conditions.length > 0 ? { conditions: input.conditions } : {},
    ...input.tempC !== void 0 ? { tempC: input.tempC } : {},
    fidelity: input.fidelity,
    ...input.fidelity === "sets" ? { sets: input.sets, ...input.matchTiebreak ? { matchTiebreak: input.matchTiebreak } : {} } : { matchScore: input.matchScore },
    ...input.status ? { status: input.status } : {},
    ...((_b = input.notes) == null ? void 0 : _b.trim()) ? { notes: input.notes.trim() } : {}
  };
}
function appendMatch(dataset, input) {
  const seq = dataset.matches.reduce((max, match2) => Math.max(max, match2.seq), 0) + 1;
  const ids = new Set(dataset.matches.map((match2) => match2.id));
  let idNumber = seq;
  while (ids.has(`match-${idNumber}`)) idNumber += 1;
  const match = buildMatchBody(input, { id: `match-${idNumber}`, seq });
  return { ...dataset, matches: [...dataset.matches, match] };
}
function replaceMatch(dataset, id, input) {
  const index = dataset.matches.findIndex((match) => match.id === id);
  if (index === -1) throw new Error(`Unknown match id: ${id}`);
  const existing = dataset.matches[index];
  const next = buildMatchBody(input, { id: existing.id, seq: existing.seq });
  const matches = dataset.matches.map((match, i) => i === index ? next : match);
  return { ...dataset, matches };
}
function serializeDataset(dataset) {
  return `${JSON.stringify(dataset, null, 2)}
`;
}
const LEAN_FACTORS = [
  { key: "headToHead", weight: 0.3, minSample: 1 },
  { key: "recentForm", weight: 0.35, minSample: 1 },
  { key: "surface", weight: 0.25, minSample: 2 },
  { key: "superTiebreaks", weight: 0.1, minSample: 2 }
];
const TOSS_UP = 0.1;
const EDGE = 0.25;
const emptyRecord = () => ({ alan: 0, opponent: 0 });
const other = (player) => player === "alan" ? "opponent" : "alan";
function deriveNextMatchLean(matches) {
  const stats = deriveOverviewStats(matches);
  const latest = stats.sortedMatches[0];
  if (!latest) return null;
  const recent = emptyRecord();
  stats.recentForm.forEach((item) => {
    recent[item.winner] += 1;
  });
  const surfaceRow = stats.surfaceSplit[latest.surface];
  const superTiebreaks = emptyRecord();
  stats.sortedMatches.forEach((match) => {
    if (match.fidelity === "sets" && match.matchTiebreak) superTiebreaks[deriveSetWinner(match.matchTiebreak)] += 1;
  });
  const records = {
    headToHead: stats.matchRecord,
    recentForm: recent,
    surface: { alan: surfaceRow.alan, opponent: surfaceRow.opponent },
    superTiebreaks
  };
  let balance = 0;
  const factors = LEAN_FACTORS.map(({ key, weight, minSample }) => {
    const record = records[key];
    const sample = record.alan + record.opponent;
    const counted = sample >= minSample;
    const share = sample ? (record.alan - record.opponent) / sample : 0;
    if (counted) balance += weight * share;
    const favours = !counted || share === 0 ? null : share > 0 ? "alan" : "opponent";
    return { key, record, favours, counted, weight };
  });
  const magnitude = Math.abs(balance);
  const verdict = magnitude < TOSS_UP ? "tossUp" : magnitude < EDGE ? "slightEdge" : "edge";
  return {
    verdict,
    favourite: verdict === "tossUp" ? null : balance > 0 ? "alan" : "opponent",
    balance,
    surface: latest.surface,
    factors
  };
}
const NUMBER_WORDS = ["No", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten"];
const numberWord = (value) => {
  var _a;
  return (_a = NUMBER_WORDS[value]) != null ? _a : String(value);
};
const titleCase = (value) => value.charAt(0).toUpperCase() + value.slice(1);
function headline(match, names, cameBack) {
  const winner = deriveMatchResult(match).winner;
  const name = names[winner];
  const court = `on ${titleCase(match.surface)}`;
  switch (deriveMatchShape(match)) {
    case "superTiebreak": {
      const points = match.matchTiebreak;
      const score = `${points[winner]}–${points[other(winner)]}`;
      return `${name} wins the super tiebreak ${score} ${court}${cameBack ? ", from a set down" : ""}.`;
    }
    case "thirdSet":
      return cameBack ? `${name} comes back from a set down ${court}.` : `${name} wins a third-set decider ${court}.`;
    case "straight":
      return `${name} wins in straight sets ${court}.`;
    case "scoreOnlyDecider":
      return `${name} wins a deciding set ${court}.`;
    default:
      return `${name} wins ${court}.`;
  }
}
function standing(winner, before, after, names, afterRun) {
  if (after.alan === after.opponent) return `level at ${after.alan}–${after.opponent}`;
  const leader = after.alan > after.opponent ? "alan" : "opponent";
  const score = `${after[leader]}–${after[other(leader)]}`;
  if (leader !== winner) return `${names[leader]} still leads ${score}`;
  const extending = before[winner] > before[other(winner)];
  if (afterRun) return extending ? `the lead grows to ${score}` : `now ahead ${score}`;
  return extending ? `${names[winner]} extends the lead to ${score}` : `${names[winner]} moves ahead ${score}`;
}
function leanLine(lean, names) {
  if (lean.verdict === "tossUp" || !lean.favourite) return "Next match: a toss-up.";
  return lean.verdict === "slightEdge" ? `Next match: ${names[lean.favourite]} slightly favoured.` : `Next match: ${names[lean.favourite]} favoured.`;
}
function deriveRivalryNote(matches, names) {
  const latest = sortMatchesNewestFirst(matches).find((match) => !isUnfinished(match));
  const lean = deriveNextMatchLean(matches);
  if (!latest || !lean) return [];
  const context = deriveMatchContext(matches, latest.id);
  const cameBack = deriveFirstSetConversion([latest]).comebackMatchIds.length > 0;
  const run = context.streakAfter.count;
  const where = standing(context.winner, context.recordBefore, context.recordAfter, names, run >= 2);
  const second = run >= 2 ? `${numberWord(run)} in a row for ${names[context.winner]} — ${where}.` : `${titleCase(where)}.`;
  return [headline(latest, names, cameBack), second, leanLine(lean, names)];
}
const REWRITES = [
  [/^cannot end with a tied match score\.$/, () => "It's one set all — enter the match tiebreak (or third set), or mark the match Unfinished."],
  [/^matchScore cannot be tied\.$/, () => "Sets won can't be level for a finished match — fix the tally, or mark the match Unfinished."],
  [/^matchScore must record at least one set\.$/, () => "Enter the sets won."],
  [/^matchScore\.(alan|opponent) must be a non-negative integer\.$/, () => "Sets won: enter a whole number for both players."],
  [/^sets must be a non-empty array\.$/, () => "Enter at least one set score."],
  [/^cannot include a tied set\.$/, () => "A set can't finish level — check the games."],
  [/^has a set after the match was already won/, () => "The match was already won in two sets — clear the extra set."],
  [/^sets\[(\d+)\] (\d+)-(\d+) is not a valid set score (.*)$/, (m) => `Set ${Number(m[1]) + 1}: ${m[2]}-${m[3]} isn't a valid set score ${m[4]}`],
  [/^sets\[(\d+)\]\.(alan|opponent) must be a non-negative integer\.$/, (m) => `Set ${Number(m[1]) + 1}: enter games for both players.`],
  [/^sets\[(\d+)\]\.tiebreak\.(alan|opponent) must be a non-negative integer\.$/, (m) => `Set ${Number(m[1]) + 1} tiebreak: enter points for both players.`],
  [/^sets\[(\d+)\]\.tiebreak (.*)$/, (m) => `Set ${Number(m[1]) + 1} tiebreak ${m[2]}`],
  [/^matchTiebreak\.(alan|opponent) must be a non-negative integer\.$/, () => "Match tiebreak: enter points for both players."],
  [/^matchTiebreak decides the match, so the match cannot be unfinished\.$/, () => "A match tiebreak decides the match — mark it Finished, or clear the tiebreak."],
  [/^matchTiebreak (.*)$/, (m) => `Match tiebreak ${m[1]}`],
  [/^tempC .*$/, () => "Temperature must be a number between -30 and 55 °C."],
  [/^date must be YYYY-MM-DD/, () => "Pick a valid date."]
];
function describeFormIssue(issue) {
  const bare = issue.replace(/^match \S+ /, "");
  for (const [pattern, rewrite] of REWRITES) {
    const found = bare.match(pattern);
    if (found) return rewrite(found);
  }
  return bare.charAt(0).toUpperCase() + bare.slice(1);
}
exports.DatasetValidationError = DatasetValidationError;
exports.SURFACES = SURFACES;
exports.WEATHER_TAGS = WEATHER_TAGS;
exports.appendMatch = appendMatch;
exports.deriveCadence = deriveCadence;
exports.deriveDataCoverage = deriveDataCoverage;
exports.deriveFirstSetConversion = deriveFirstSetConversion;
exports.deriveGamesTally = deriveGamesTally;
exports.deriveMatchContext = deriveMatchContext;
exports.deriveMatchResult = deriveMatchResult;
exports.deriveMatchShape = deriveMatchShape;
exports.deriveNextMatchLean = deriveNextMatchLean;
exports.deriveOverviewStats = deriveOverviewStats;
exports.deriveRivalryNote = deriveRivalryNote;
exports.deriveScorelineDistribution = deriveScorelineDistribution;
exports.deriveSetWinner = deriveSetWinner;
exports.deriveSurfaceForm = deriveSurfaceForm;
exports.deriveTimeline = deriveTimeline;
exports.describeFormIssue = describeFormIssue;
exports.formatMatchScore = formatMatchScore;
exports.formatMatchTiebreak = formatMatchTiebreak;
exports.formatNeutralScoreline = formatNeutralScoreline;
exports.formatSetScore = formatSetScore;
exports.formatWinnerScoreline = formatWinnerScoreline;
exports.isUnfinished = isUnfinished;
exports.longestRun = longestRun;
exports.matchGamesTally = matchGamesTally;
exports.maxLead = maxLead;
exports.replaceMatch = replaceMatch;
exports.serializeDataset = serializeDataset;
exports.sortMatchesNewestFirst = sortMatchesNewestFirst;
exports.validateDataset = validateDataset;
